; CHAPTER 1 EXERCISES

; [1.1] translate this into prefix form
;
; 5 + 4 + (2 - (3 - (6 + 4/5)))
; -----------------------------
; 3(6-2)(2-7)
;

(/ 
  (+ 5 4 (- 2 (- 3 (+ 6 (/ 4 5))))) 
  (* 3 (- 6 2) (- 2 7)))

; [1.3]
; Define a procedure that takes 3 numbers as args and returns the sum of the squares of the two larger numbers.
; 2 3 -1, that's an edge case. the middle number is compared twice.
;
; 

(define (square x) (* x x))
(define (max x y) (if (>= x y) x y)) 
(define (largest)
(define (f x y z)
  (if (> x y) 
    (+ (square x) (square (max y z)))
    (+ (square y) (square (max x z)))
  ))

; [1.5]
; What happens if the following code is run in an applicative evaluation model versus a normative model?
;
; (define (p) (p))
; (define(test x y)
;   (if(= x 0)
;     0
;     y))
;
; (test 0 (p))
;
;
; Answer:
; In an applicative evaluation model, (test 0 (p)) never finishes because p is evaluated in every case, regardless of the value of x.  
; In a normal-order evaluation model, it will return 0 because x is 0. Y will never get evaluated.

; Why does writing a 'new-if' function in terms of 'cond' pose a problem when calculating square roots recursively via Netwon's method?
; Answer: the standard 'if' is normal-order evaluation, and only ever evaluates one of its operands, but 'cond', which is applicative order, evaluates them all, so the recursive call will be evaluated in every case.

; [1.9]
; given these two functions, illustrate substitution model generated by each. are they recursive or iterative?
;
; A:
;(define (plus a b)
; (if (= a 0) 
;     b 
;     (inc (plus (dec a) b))))
;
;(plus 4 5)
;(inc (plus 3 5))
;(inc (inc (plus 2 5)))
;(inc (inc (inc (plus 1 5))))
;(inc (inc (inc (inc (plus 0 5)))))
;(inc (inc (inc (inc (5)))))
;(inc (inc (inc 6)))
;(inc (inc 7))
;(inc 8)
;9
 

; B: 
;(define (plus a b)
; (if (= a 0) 
;     b 
;     (plus (dec a) (inc b))))
;
;
; (plus 4 5)
; (plus 3 6)
; (plus 2 7)
; (plus 1 8)
; (plus 0 9)
;
;
;
;[1.10]
; Given Ackerman's function:
;
;(define (A x y)
; (cond ((= y 0) 0)
;       ((= x 0) (* 2 y))
;       ((= y 1) 2)
;       (else (A (- x 1)
;                (A x (- y 1))))))
;
; What are the values of the following expressions?
; - (A 1 10)               
; 
; (A 1 10)
;
; (A 0 (A 1 9))
; (* 2 (A 1 9))
;
; (* 2 (A 0 (A 1 8)))
; (* 2 (* 2 (A 0 (A 1 7))))
; (* 2 (* 2 (* 2 (A 0 (A 1 6)))))
; (* 2 (* 2 (* 2 (* 2 (A 0 (A 1 5))))))
; (* 2 (* 2 (* 2 (* 2 (* 2 (A 0 (A 1 4)))))))
; (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 (A 0 (A 1 3))))))))
; (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 (A 0 (A 1 2)))))))))
; (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 (A 0 (A 1 1))))))))))
; (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 (A 0 2)))))))))
; (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 2)))))))))
; (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 4))))))))
; (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 8)))))))
; (* 2 (* 2 (* 2 (* 2 (* 2 (* 2 16))))))
; (* 2 (* 2 (* 2 (* 2 (* 2 32)))))
; (* 2 (* 2 (* 2 (* 2 64))))
; (* 2 (* 2 (* 2 128)))
; (* 2 (* 2 256))
; (* 2 512)
; 1024
;
;

;
; - (A 2 4)               
; - (A 3 3)               
;
;



